language: node_js

sudo: false

notifications:
  email: false

node_js:
  - '8'
  - '9'

branches:
   only:
     - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

stages:
  - test
  - coverage

script: echo "Running tests against $(node -v)"

jobs:
  include:
    - stage: coverage
      node_js: '9'
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
