version: 2.0

jobs:
  build:
    docker:
      - image: canopycanopycanopy/b-ber:0.2.0
    branches:
      only:
        - master
    working_directory: ~/b-ber
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: |
          yarn config set user root --global
          yarn add global lerna
          yarn
          lerna bootstrap
          yarn build
          yarn test
          cd ~
          $BBER --version
          $BBER new foo
          cd foo
          $BBER theme list
          $BBER theme set b-ber-theme-serif
          $BBER build
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
